# Steam API

In [1]:
# we will use an API to get steam data
# we will use Steam Spy API to extract most popular games,price,developer etc.

import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import json
import time

In [ ]:
# this retuns data for the first page in jason format
url= 'https://steamspy.com/api.php?request=all&page=0'
response = requests.get(url)
data = response.json()

In [15]:
df = pd.DataFrame.from_dict(data, orient='index')
df

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
730,730,Counter-Strike: Global Offensive,Valve,Valve,,7642084,1173003,0,"100,000,000 .. 200,000,000",34112,731,6777,297,0,0,0,1013936
1172470,1172470,Apex Legends,Respawn,Electronic Arts,,668053,326926,0,"100,000,000 .. 200,000,000",11025,635,977,256,0,0,0,124262
578080,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",,1520457,1037487,0,"100,000,000 .. 200,000,000",23333,820,5899,335,0,0,0,314682
1623730,1623730,Palworld,Pocketpair,Pocketpair,,358266,22443,0,"50,000,000 .. 100,000,000",3930,770,2223,397,2249,2999,25,18028
440,440,Team Fortress 2,Valve,Valve,,1044264,117208,0,"50,000,000 .. 100,000,000",21058,772,4175,161,0,0,0,43819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668580,668580,Atomic Heart,Mundfish,"Focus Entertainment, 4Divinity",,31167,6828,0,"1,000,000 .. 2,000,000",890,130,531,123,1799,5999,70,466
1044720,1044720,Farthest Frontier,Crate Entertainment,Crate Entertainment,,16780,2724,0,"1,000,000 .. 2,000,000",2584,527,801,603,3499,3499,0,995
544750,544750,SOULCALIBUR VI,"BANDAI NAMCO Studios Inc., Dimps Corporation",BANDAI NAMCO Entertainment,,11147,2394,0,"1,000,000 .. 2,000,000",992,97,168,97,599,5999,90,119
972660,972660,Spiritfarer: Farewell Edition,Thunder Lotus,Thunder Lotus,,44192,2225,0,"1,000,000 .. 2,000,000",885,212,407,405,2999,2999,0,702
1150690,1150690,OMORI,"OMOCAT, LLC","OMOCAT, LLC",,78023,2214,0,"1,000,000 .. 2,000,000",1323,91,853,91,1999,1999,0,506

# now we will request most popular Steam games in 10 pages

In [ ]:
from time import time


all_dfs = []
for i in range(10):
    url = f'https://steamspy.com/api.php?request=all&page={i}'
    response = requests.get(url)
    data = response.json()
    df = pd.DataFrame.from_dict(data, orient='index')
    all_dfs.append(df)
    time.sleep(10)  # to avoid overwhelming the server

full_df = pd.concat(all_dfs, ignore_index=True)

In [25]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            10000 non-null  int64
 1   name             10000 non-null  object
 2   developer        10000 non-null  object
 3   publisher        10000 non-null  object
 4   score_rank       10000 non-null  object
 5   positive         10000 non-null  int64
 6   negative         10000 non-null  int64
 7   userscore        10000 non-null  int64
 8   owners           10000 non-null  object
 9   average_forever  10000 non-null  int64
 10  average_2weeks   10000 non-null  int64
 11  median_forever   10000 non-null  int64
 12  median_2weeks    10000 non-null  int64
 13  price            10000 non-null  object
 14  initialprice     10000 non-null  object
 15  discount         10000 non-null  object
 16  ccu              10000 non-null  int64
dtypes: int64(9), object(8)
memory usage: 1.3+ MB

In [26]:
full_df.head(10)

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,730,Counter-Strike: Global Offensive,Valve,Valve,,7642084,1173003,0,"100,000,000 .. 200,000,000",34112,731,6777,297,0,0,0,1013936
1,1172470,Apex Legends,Respawn,Electronic Arts,,668053,326926,0,"100,000,000 .. 200,000,000",11025,635,977,256,0,0,0,124262
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",,1520457,1037487,0,"100,000,000 .. 200,000,000",23333,820,5899,335,0,0,0,314682
3,1623730,Palworld,Pocketpair,Pocketpair,,358266,22443,0,"50,000,000 .. 100,000,000",3930,770,2223,397,2249,2999,25,18028
4,440,Team Fortress 2,Valve,Valve,,1044264,117208,0,"50,000,000 .. 100,000,000",21058,772,4175,161,0,0,0,43819
5,1938090,Call of Duty: Modern Warfare II,"Treyarch, Raven Software, Beenox, High Moon St...",Activision,,419594,294520,0,"50,000,000 .. 100,000,000",5752,426,665,181,3849,6999,45,67419
6,1063730,New World: Aeternum,Amazon Games,Amazon Games,,196798,90080,0,"50,000,000 .. 100,000,000",10917,1225,3313,334,5999,5999,0,5583
7,2358720,Black Myth: Wukong,Game Science,Game Science,,1111720,38378,0,"50,000,000 .. 100,000,000",3198,118,2780,73,5999,5999,0,15004
8,271590,Grand Theft Auto V Legacy,Rockstar North,Rockstar Games,,1739980,250576,0,"50,000,000 .. 100,000,000",14086,900,5576,120,0,0,0,67851
9,550,Left 4 Dead 2,Valve,Valve,,940221,23762,0,"50,000,000 .. 100,000,000",2565,369,528,104,999,999,0,25122

In [27]:
full_df.to_csv('../data/steam_spy_data.csv', index=False)

# we have the full data saved as csv we will use it with the metacritic data we scraped